# Generated by Django 6.0.3 on 2026-03-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='category_id',
            field=models.IntegerField(),
        ),
    ]
